from Aspirador import Aspirador
import functions
import sys

# Aspirador Inteligente.
print("""Informe os dados de entrada para o aspirador inteligente.
    Os dados são compostos por um par de linha conforme exemplo:
                                                            +-----------------+
    Linha 1 informe a largura e comprimento do ambiente  => | 5 5             |
                                                            +-----------------+
    Linha 2 informe a seguência dos passos               => | FDFEFDFEFDFEFDF |
                                                            +-----------------+
    Você pode informar quantos ambientes desejar.
    
    """)

# Lê os dados de entrada.
data = functions.getData()

for item in data:
    # Entrada de dados da posição inicial do aspirador.
    initial_position = [0, 0]

    # Posição inicial do aspirador.
    currentDirection = "N"
     
    # Criando o objeto aspirador.    
    aspirador = Aspirador(currentDirection=currentDirection, current_position=initial_position, dimensions=item['dimensions'], move=item['move'])
   
    # Executa a sequencia de movimentos e retorna o resultado.
    aspirador.ExecuteMove()

    # Exibe o resultado.
    print(aspirador.Result())
    
    # remove o objeto da memória.
    aspirador.__destroy__()



# Exemplo de entrada:
""" 
50 50
TTFFDTTETDEDTTDDFFDEFDTEFTTDDEDEFFTEETEDTTEE
DDEFFFTEDFDFTTDDDTTTTTFDEFDFFTEDTEDEFTDTETETF
DFTDTFEFDTFTTEEFEEFEDDTFTEDFFTTDTTTFDETETDDTE
DDTFEDFDEFDDTTDEFEFTDTTDFFEDDTDFDETTDDFFTEED
FFTTTDETFTFDTETTTTDEFFETFTDFDTEEDFTEFTEFFFTDE
EDDTTEFDFETDFEEETTDFTTTEEEEEDTETFETTETDEEFTTD
DDFFTFDDEFDEFTTTEDFFFTEEDTDDTTDFDEETTDETETDD
ETTTDEFEETTETDEDTEFTTDDEEFDFDTEEEDEDTDDTEEEE
EDTFEDEDDDTTTFFDETFFDDTFDTEFFFDDFEEFEFDDFDTT
ETTDTDTTTDEDFTTDDDTTTTTDTEDFEFDTFFETEEEFFFEFD
TTDETTFFETTDEETFEDTEFFDEEFEEDTTFFTEEETDTEEEFT
FFEFEFDFFEFTFEDEEDFDDDFDFEFEDDDTEETTETFTTFDT
DEFTFEEDEFTEFETFEEEFDETEDFFTFDFFTFDTFEFDEDTTT
FEDEFTTDDEEFDTFTEEDTETEFEFFEEEFFTFEETEDDFFFTF
DETFDEFETDTFDDFFTFDTFTTFTTFDFDDEDEFFFETTTTFFF
FTDEEEFTDFDDFTFETDDEDFFFEFFDDDTTDEFETFDEFDED
ETDFEETEDTFETTTFEEEFTETFFTDFDFEDFTDDTEFTFFEFE
EFTTTFEEFTDDDEEDTFTFDTTDFDEETFFTDFDEDEEFFDTFE
TEDEETTEFFFDETTTFTEETFDTEFFEEFFDEDFFDTTEFDETD
DETDDDTDFETTTETEEEFDFTEETDTEDETTEDETFEEEFTFFE
EDTFFFTEDDFDDFDDTTEDEETETEEFDDDTTTTTEEFEFFFTE
FEDEFEFEFEDDFFEEEFEETTFDFEEDDTTTTETDTEDEFFDFT
TFFTDTEDEDEDDFEFT
1000 1000
EDFFEDFTTEDFTETEFDTFDTDTDTFDFTDEDTFFTFTDDDETF
TFEFETEFEEEDFTTEFEEDFTFFTFTDTTDFDDDTFTTTDDEET
DDFTDFFETTDTTTFEEFFTDTFETDEFEDEFDFDTTEFDEEDTT
DDETTDEDTTEEEFFEEDDDETDFDTEDEDFTFFEEDEDDFEDE
DFDDFEDEETTFTETFTTTEETTFDDTTEFDDEDTDEDEDDFTF
EFTDFEFFDTETFFFTDTFTEFFFEDETFETTFETDFFFDEETETF
EFFTFETFEFFTEETDETDEFEFTFDEEFDEEDTEDEFEFTEETT
TTFEEFTDTDDFDEDFEDDDDTEDDDTFDDDEEEEDTTDFEDT
DETFTFTFDFTFTDFEDEFDEEEDDETEEEDDTEFEFFFDTEFTF
FEETETEDDDDEFTEEDDEDDTTDTTEDFEFETFTDTFTFEEDE
FEDTEFDEEDEDEFDTEDEETEDEDEDDEDTDTDDFFEFDEET
TEDDEFFTFDEFEFFDFDDTFEFTTDDDTDTDDFDEEDETDDDF
EFTEDEFEEFDETEFTDFTFDDFTFEEDEEEEEDDDTEDDFTDF
DFFFDTETTTDETTEDETEDDETETDEEFTTFTDDFDEEEFFDE
DTEDFTEETTEFDDFTFEFEEEETFTEFTEDFTFFEEEDFDETTE
FDTFFDDDFFDTEEFETDTETFDFTDEDTFFFFEETTFDFDDFTD
TTDFFTFDDDTDTDDFDDEETETTFETTEFDTTFEDDFDTEDET
TTEDTDEFFEFFFTDTEDTTTEFFTTTTDFTDFTETDDFDEEFEF
TEFTTDDDTEFEFETDDDDTETTTETEEDEETTDDFTDTETTFTF
FTEFFEEDEEEFTTDEEEEFEDTEEEDEEDDDTETEFEFDDDED
EFEFTTDFDTTDEDFTFDDTDTFDDDDEFEEEDEDDTTTDDTED
TEDDTDTDDTFETDTDTDFDDDTTEEEFEDTEFFDEEDTTEFTD
EDTDDETEFEFEFFTTTEEFDEF
"""


# Saída esperada.
# S 11 13
# L 25 5
