import Head from 'next/head'
import styles from '../styles/Home.module.css'
import { Header } from '../components/Header'
import { Banner } from '../components/Banner'
import { Section } from '../components/Section'

const Home = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>NTFs | L2</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <meta name="viewport" content="width=device-width, initial-scale=0.4" />
      </Head>

      <Header
        label="NTFs"
        color="#000"
        onClick={() => { }}
        fill={true}
      />
      <div className={styles.latestAuctions}>
        <h4>Latest live auctions</h4>
        <div className={styles.itens}>
          <Banner
            onClick={() => { }}
          />
        </div>
      </div>
      <Section/>

      <footer className={styles.footer}>
        footer
      </footer>
    </div>
  )
}

export default Home
