import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import {Header} from '../components/Header'

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>NTFs | L2</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header 
        label="NTFs"
        color="#000"
        onClick={() => {}}
        fill={true}
        
      />

      <main className={styles.main}>
        main
      </main>

      <footer className={styles.footer}>
         footer
      </footer>
    </div>
  )
}

export default Home
